info voor dojo #69 toegevoegd
coderdojonijmegen/hugo-coderdojo-nijmegen pull request #10
Opened 2020-08-24 21:05 UTC by pfbuur

2020-08-24 21:05 UTC, pfbuur commented
@bashopman wil jij even kijken of dit zo ok lijkt?

2020-08-25 05:52 UTC, bashopman requested changes
Ziet er goed uit! Wel een paar kleine vraagjes/opmerkingen. ;)

Hieronder een screenshot van hoe het er uit komt te zien op de site.
Zie ook de inschrijfknop. Deze verdwijnt als we de site nog eens deployen na de uiterste inschrijfdatum.

![image](https://user-images.githubusercontent.com/7276252/91127783-4765c400-e6a7-11ea-90ef-e30b401ef1fa.png)

2020-08-25 05:52 UTC, bashopman commented on content/dojos/68-robots.md
> +date: 2020-09-05T0:0:0+01:00
Dit zou de creëer/publicatie datum moeten zijn, maar functioneel maakt het niet zoveel uit.

2020-08-25 05:52 UTC, bashopman commented on content/dojos/68-robots.md
> +title: "#68 robots"
Willen we hoofdletters beginnen of met kleine letters (zie eerste 2 en laatste 2 dojos):
![image](https://user-images.githubusercontent.com/7276252/91127660-ffdf3800-e6a6-11ea-8df3-e71dbdcfa626.png)

2020-08-25 05:52 UTC, bashopman commented on content/dojos/68-robots.md
> +Neem een laptop mee, en installeer om snel aan de slag te kunnen de [micro:bit offline app](https://makecode.microbit.org/offline-app) en het [mBlock programma](https://mblock.makeblock.com/en-us/dow
Zouden we hier ook het Corona stukje (zoals op EventBrite) nog bij moeten zetten?

2020-08-25 12:56 UTC, bashopman commented
> Zie ook de inschrijfknop. Deze verdwijnt als we de site nog eens deployen na de uiterste inschrijfdatum.
https://github.com/coderdojonijmegen/hugo-coderdojo-nijmegen/pull/11 zorgt ervoor dat de site iedere dag op 0:00 wordt bijgewerkt en dat de knop dus 's nachts verdwijnt.

2020-08-26 05:26 UTC, bashopman commented on content/dojos/68-robots.md
> +title: "#68 robots"
Gekozen voor hoofdletters.

2020-08-26 05:27 UTC, bashopman commented on content/dojos/68-robots.md
> +Neem een laptop mee, en installeer om snel aan de slag te kunnen de [micro:bit offline app](https://makecode.microbit.org/offline-app) en het [mBlock programma](https://mblock.makeblock.com/en-us/dow
Toegevoegd.

2020-08-26 05:29 UTC, merged